#!/bin/bash

set -e
set -o pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source /opt/resource/common.sh

# Read inputs
target=$1
payload=$(mktemp helm-resource-request.XXXXXX)
cat > $payload <&0

# Prepare
setup_resource $payload $source
echo "Resource setup successful."

# Parse parameters
namespace=$(jq -r '.source.namespace // "default"' < $payload)
tiller_namespace=$(jq -r '.source.tiller_namespace // "kube-system"' < $payload)
release_file=$(jq -r '.params.release // ""' < $payload)
if [ -n "$release_file" ]; then
  release=`cat $source/$release_file`
else
  release=$(jq -r '.source.release // ""' < $payload)
fi

is_deployed() {
  if [ -n "$1" ]; then
    set +e
    set +o pipefail
    helm history --tiller-namespace $tiller_namespace $1 2>&1 | grep "DEPLOYED" > /dev/null
    if [ $? = 0 ]; then
      # exists
      echo true
    else
      # does not exist
      echo false
    fi
    set -o pipefail
    set -e
  else
    echo false
  fi
}

# Find the current revision of a helm release
current_revision() {
  revision=`helm history --tiller-namespace $tiller_namespace $release | grep "DEPLOYED" | awk '{print $1}'`
  echo $revision
}

if [ "$(is_deployed $release)" = true ]; then
	helm status $release | tee $target/status
fi
echo '{"version":{"ref":"none"}}' >&3
